web/router.ex
defmodule FitbitClient.Router do
  use FitbitClient.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :assign_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", FitbitClient do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    get "/sync", FitbitAuthController, :fitbit_sync
  end

  scope "/auth/fitbit", FitbitClient do
    pipe_through :browser
    get "/", FitbitAuthController, :index
    get "/callback", FitbitAuthController, :callback
    delete "/logout", FitbitAuthController, :delete
  end

  scope "/auth/caren", FitbitClient do
    pipe_through :browser
    get "/", CarenAuthController, :index
    get "/callback", CarenAuthController, :callback
    delete "/logout", CarenAuthController, :delete
  end

  defp assign_current_user(conn, _) do
    assign(conn, :current_user, get_session(conn, :current_user))
  end
end

web/views/layout_view.ex
defmodule FitbitClient.LayoutView do
  use FitbitClient.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Kevin Etore <kevin.etore@nedap.com> Harmen Aversteeg <h.aversteeg@nedap.com>">
    <title>Caren Fitbit Syncer</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <link rel="apple-touch-icon" sizes="57x57" href="<%= static_path(@conn, "/images/apple-icon-57x57.png") %>">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= static_path(@conn, "/images/apple-icon-60x60.png") %>">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= static_path(@conn, "/images/apple-icon-72x72.png") %>">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= static_path(@conn, "/images/apple-icon-76x76.png") %>">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= static_path(@conn, "/images/apple-icon-114x114.png") %>">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= static_path(@conn, "/images/apple-icon-120x120.png") %>">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= static_path(@conn, "/images/apple-icon-144x144.png") %>">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= static_path(@conn, "/images/apple-icon-152x152.png") %>">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= static_path(@conn, "/images/apple-icon-180x180.png") %>">
    <link rel="icon" type="image/png" sizes="192x192"  href="<%= static_path(@conn, "/images/android-icon-192x192.png") %>">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= static_path(@conn, "/images/favicon-32x32.png") %>">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= static_path(@conn, "/images/favicon-96x96.png") %>">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= static_path(@conn, "/images/favicon-16x16.png") %>">
    <link rel="manifest" href="<%= static_path(@conn, "/images/manifest.json") %>
    <meta name="msapplication-TileColor" content="#3c1275">
    <meta name="msapplication-TileImage" content="<%= static_path(@conn, "/images/ms-icon-144x144.png") %>">
    <meta name="theme-color" content="#3c1275">
  </head>
  <body>
    <div class="wrapper">
      <header class="topbar">
        <div class="topbar__left"></div>
        <div class="topbar__right">
          <%= if @current_user do %>
            <span class="topbar__username"><%= @current_user.name %></span>
            <%= link("Logout", to: fitbit_auth_path(@conn, :delete), method: :delete, class: "btn btn-sm topbar__logout") %>
          <% end %>
        </div>
      </header>
      <section class="container content__wrapper">
        <!-- <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p> -->
        <main role="main">
          <header class="header">
            <h3>Caren Fitbit Syncer</h3>
          </header>
          <%= render @view_module, @view_template, assigns %>
        </main>
      </section>
      <section class="canvas__wrapper">
        <div id="canvas" class="canvas__gradient"></div>
      </section>
      <footer class="footer">
        <div class="footer__content">
          <a href="https://www.carenzorgt.nl" class="footer__logo" target="_blank">Caren</a>
          <span class="footer__copyright">&copy; Caren 2017</span>
          <a href="https://www.carenzorgt.nl/terms-of-service" class="footer__disclaimer" target="_blank">Disclaimer</a>
          <span>Want to build your own awesome app for Caren? <a href="https://developer.carenzorgt.nl/docs" target="_blank">Read the Docs</a> for more information.</span>
        </div>
      </footer>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>